In [1]:
import numpy as np

In [2]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [3]:
b=np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
c=b[::-1]
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [5]:
d=np.arange(0, 9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
e=np.array([1,2,0,0,4,0])
np.where(e==0)

(array([2, 3, 5]),)

In [7]:
f=np.random.random(30)
print(f)
print('Mean= ', np.mean(f))

[0.26135202 0.28822757 0.87325119 0.81275416 0.5597333  0.54994298
 0.11265488 0.0772369  0.65723986 0.60284602 0.38422853 0.76822062
 0.62577046 0.5481796  0.98857492 0.81646134 0.16260608 0.04683014
 0.88664572 0.5717908  0.24432039 0.01037064 0.77167571 0.18068307
 0.31010455 0.13377141 0.47205495 0.25737513 0.72258378 0.59757929]
Mean=  0.4765022008508092


In [8]:
g = np.ones((5,5))
g[1:-1,1:-1] = 0
g

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
h = np.ones((8,8))

h = np.zeros((8,8),dtype=int)
h[1::2,::2] = 1
h[::2,1::2] = 1
h

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
I=np.array((0,1, 1, 0)).reshape(2,2)

I_tile = np.tile(I, (4, 4))
print(I_tile)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [11]:
Z = np.arange(11)
j = (Z >= 3) & (Z <= 8)
Z[j] *= -1
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [12]:
Z = np.random.random(10)
k=np.sort(Z)
print(k)

[0.04370198 0.12263938 0.25565609 0.42181898 0.52776338 0.57250682
 0.58428709 0.58820558 0.76919915 0.84459395]


In [13]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A==B

array([False,  True,  True, False,  True])

In [32]:
Z = np.arange(10, dtype='int32')
print(Z.dtype)
Z = Z.astype('float32')
print(Z.dtype)

int32
float32


In [28]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D =np.diag(C)

print(D)

[ 18  66 132]


## Optimization of the code from day 2

In [93]:
%timeit AA=np.random.randint(0,100, 250*250).reshape(250, 250)
BB=np.random.randint(0,100, 250*250).reshape(250, 250)

print(AA*BB)
%timeit

482 µs ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[[1680 2607 1900 ... 1715   96  328]
 [ 666 5766  400 ... 6240  575  142]
 [1743   36 3552 ... 4524 5310 5184]
 ...
 [ 132  342 2484 ...  756  470  646]
 [7802 7448 2052 ... 4968  731   30]
 [ 640 3640 3850 ... 3564  759 2592]]
